---
collections:

  - name: ansible.netcommon
  - name: ansible.utils
  - name: community.network
  - name: cisco.ios
  - name: fortinet.fortios
  

  - name: ansible.windows
  - name: ansible.posix
  - name: community.windows
  - name: microsoft.ad


  - name: azure.azcollection
  - name: maxhoesel.proxmox
  - name: community.docker
  

  - name: community.zabbix
  - name: grafana.grafana

  - name: community.crypto

  - name: community.general
  - name: community.dns
  - name: community.saplibs
  - name: ansible.eda
